Trying to fix the solver-then-new-var batman-returns bug.
underworldcode/underworld3-archive pull request #156
Opened 2024-02-14 06:34 UTC by lmoresi

Very silly (global v. local) bugs in the dm updates associated with new variables. Fixing for parallel solve() / mesh var ordering. This should help with meshes that need to make a solve as part of their setup (e.g. for the surface normals to be projected).

Update to use some new petsc option names. 
Examples with projected normals for irregular boundaries.
Comparisons of faceted normals, analytic normals, projected normals for several cases.

2024-02-14 22:19 UTC, julesghub requested changes
Looks good to me. Are the tests passing? Please review my feedback

2024-02-14 22:19 UTC, julesghub commented on Jupyterbook/Notebooks/Examples-PorousFlow/Ex_Darcy_1D_benchmark.py
This change of index looks and `=-` looks significant. Please confirm

2024-02-14 22:19 UTC, julesghub commented on underworld3/cython/petsc_generic_snes_solvers.pyx
> +            self.dm_hierarchy = [None]
Why not just `dm_hierarchy = []`?

2024-02-14 22:33 UTC, lmoresi commented on Jupyterbook/Notebooks/Examples-PorousFlow/Ex_Darcy_1D_benchmark.py
There are two examples in the one notebook and perhaps this should be via a flag instead (see tests) ... I'll change it.

2024-02-14 23:22 UTC, lmoresi commented on underworld3/cython/petsc_generic_snes_solvers.pyx
> +            self.dm_hierarchy = [None]
This is one of those bits of code that is probably not needed at all. 

self.dm_hierarchy should be a list. If there is no hierarchy, then self.dm_hierarchy = [self.dm] ... I'm doing this to try to catch errors that might come later after using a _reset()'d solver. (thyagi mentioned this was not working as expected).

2024-02-15 00:45 UTC, julesghub commented on underworld3/cython/petsc_generic_snes_solvers.pyx
> +            self.dm_hierarchy = [None]
ok - maybe we should just check the length of the list then, rather than put `None` values in it.
Either way I'm happy to accept it.

2024-02-15 01:03 UTC, lmoresi commented
@julesghub - Darcy notebook now computes both g and no g examples. 
@julesghub - You can make a call on the dm_hierarchy. It might not really be needed.

I found a couple more PETSc.CreateFE communicators that needed fixing.  Tests passing individually so I wrote a short script to batch them up. @julesghub - maybe we can collect up the error codes and have this script pass or fail.

2024-02-15 05:17 UTC, julesghub approved these changes

2024-02-15 05:48 UTC, merged